plugins {
    id 'jacoco'
}

tasks.withType(Test).configureEach {
    finalizedBy tasks.named('jacocoTestReport')
}

tasks.named('jacocoTestReport') {
    onlyIf { sourceSets.main.output.classesDirs.files.any { it.exists() && it.listFiles() } }
    reports {
        xml.required = true
        html.required = true
        csv.required = false
    }
}

tasks.named('jacocoTestCoverageVerification') {
    onlyIf { sourceSets.main.output.classesDirs.files.any { it.exists() && it.listFiles() } }
    violationRules {
        rule {
            enabled = true
            element = 'BUNDLE'
            limit {
                counter = 'LINE'
                value = 'COVEREDRATIO'
                minimum = BigDecimal.valueOf(0.70)
            }
        }
    }
}

tasks.named('check') {
    dependsOn tasks.named('jacocoTestCoverageVerification')
}
