package io.github.mundanej.mxjb.generator.core.diagnostics;

/** Stable diagnostic identifiers for schema compiler failures. */
public enum DiagnosticCode {
  SCHEMA_RESOURCE_NETWORK_DENIED,
  SCHEMA_RESOURCE_OUTSIDE_LOCAL_ROOT,
  SCHEMA_RESOURCE_NOT_FOUND,
  SCHEMA_RESOURCE_IO_ERROR,
  SCHEMA_RESOURCE_XML_ERROR,
  SCHEMA_RESOURCE_CYCLE,
  SCHEMA_RESOURCE_MISSING_LOCATION,
  SCHEMA_FRONTEND_UNSUPPORTED_PROFILE,
  SCHEMA_FRONTEND_UNSUPPORTED_CONSTRUCT,
  SCHEMA_FRONTEND_XML_ERROR,
  SCHEMA_FRONTEND_EXPECTED_SCHEMA_ROOT,
  SCHEMA_IR_MISSING_NAME,
  SCHEMA_IR_DUPLICATE_COMPONENT,
  SCHEMA_IR_UNRESOLVED_REFERENCE,
  SCHEMA_IR_NAMESPACE_CONFLICT,
  SCHEMA_IR_INVALID_CARDINALITY,
  SCHEMA_IR_INVALID_COMPONENT,
  SCHEMA_BINDING_INVALID_CONFIGURATION,
  SCHEMA_BINDING_UNSUPPORTED_TYPE,
  SCHEMA_BINDING_INVALID_MODEL
}
